/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface.Electrity;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Organisation.Organisation;
import Business.Organisation.OrganisationDirectory;
import Business.Role.Role;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mansi
 */
public class CreateGovernmentOrganisationAdminJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateGovernmentOrganisationAdminJPanel
     */
    private OrganisationDirectory organizationDir;
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    
    CreateGovernmentOrganisationAdminJPanel(JPanel userProcessContainer, Enterprise enterprise) 
    {
      initComponents();
      this.userProcessContainer = userProcessContainer;
      this.organizationDir = enterprise.getOrganisationDirectory();
      this.enterprise= enterprise;
      populateTable();
      populateRoleComboBox();
      populateOrgComboBox();
    }
    
    public void populateTable() {

        DefaultTableModel model = (DefaultTableModel) OrganizationJTable.getModel();

        model.setRowCount(0);

        for (Organisation organization : enterprise.getOrganisationDirectory().getOrganizationlist()) {
            for (Employee ee : organization.getEmpList().getEmployeeDirectory()) {
                Object row[] = new Object[3];
                row[0] = ee.getEmpUserAcc().getUserName();
                row[1] = ee.getEmpUserAcc().getRole();
                row[2]= ee.getEmpUserAcc().getPassword();
                model.addRow(row);
            }
        }
    }


    public void populateRoleComboBox() {
        RoleComboBox.removeAllItems();
        for(Organisation o: organizationDir.getOrganizationlist())
        {
            for(Role role: o.getSupportedRole())
           {
                RoleComboBox.addItem(role);
           }
            
        }
    }   
    
    public void populateOrgComboBox()
    {
        OrganisationComboBox.removeAllItems();
        for(Organisation o: organizationDir.getOrganizationlist())
        {
                OrganisationComboBox.addItem(o);
            
        }
    }
        


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        OrganizationJTable = new javax.swing.JTable();
        RoleComboBox = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        nameTXT = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        OrganisationComboBox = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        usernameJTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        passwordJPasswordField = new javax.swing.JPasswordField();
        submitJButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Manage Organisations Admin");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 11, -1, -1));

        OrganizationJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "UserName", "Role", "Password"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(OrganizationJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 64, 523, 95));

        RoleComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RoleComboBoxActionPerformed(evt);
            }
        });
        add(RoleComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 321, 185, -1));

        jLabel5.setText("Name:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 272, -1, 31));
        add(nameTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 277, 185, -1));

        jLabel1.setText("Organisation:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 177, -1, -1));

        OrganisationComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        OrganisationComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrganisationComboBoxActionPerformed(evt);
            }
        });
        add(OrganisationComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 179, 185, -1));

        jLabel2.setText("Username");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 209, -1, -1));

        jLabel7.setText("Role");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 321, -1, -1));
        add(usernameJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 210, 185, -1));

        jLabel4.setText("Password");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 241, -1, 20));
        add(passwordJPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 241, 185, -1));

        submitJButton.setText("Submit");
        submitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitJButtonActionPerformed(evt);
            }
        });
        add(submitJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 359, 185, -1));

        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 359, -1, -1));
    }// </editor-fold>                        

    private void RoleComboBoxActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void OrganisationComboBoxActionPerformed(java.awt.event.ActionEvent evt) {                                                     
        // TODO add your handling code here:
    }                                                    

    private void submitJButtonActionPerformed(java.awt.event.ActionEvent evt) {                                              

        Role role=  (Role) RoleComboBox.getSelectedItem();
        Organisation o = (Organisation) OrganisationComboBox.getSelectedItem();
        String username = usernameJTextField.getText();
        String password = String.valueOf(passwordJPasswordField.getPassword());
        String name = nameTXT.getText();

        Employee employee = o.getEmpList().createEmployee(name,role);
        //employee.setRole(role);
        UserAccount ua = new UserAccount();
        ua.setEmployee(employee);
        ua.setPassword(password);
        ua.setRole(role);
        ua.setUserName(username);
        o.getUserAccountDir().addUserAccount(ua);
        employee.setEmpUserAcc(ua);
        JOptionPane.showMessageDialog(null, "Added Successfully..!!");

        populateTable();
    }                                             

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {                                            
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        //SystemAdminWorkAreaJPanel sysAdminwjp = (SystemAdminWorkAreaJPanel) component;
        //sysAdminwjp.populateTree();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }                                           


    // Variables declaration - do not modify                     
    private javax.swing.JComboBox OrganisationComboBox;
    private javax.swing.JTable OrganizationJTable;
    private javax.swing.JComboBox RoleComboBox;
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nameTXT;
    private javax.swing.JPasswordField passwordJPasswordField;
    private javax.swing.JButton submitJButton;
    private javax.swing.JTextField usernameJTextField;
    // End of variables declaration                   

}

/**
 *
 * @author mansi
 */
//public class CreateGovernmentOrganisationAdmin extends javax.swing.JFrame {

    /**
     * Creates new form CreateGovernmentOrganisationAdmin
     */
    //public CreateGovernmentOrganisationAdmin() {
        //initComponents();
    //}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    //public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateGovernmentOrganisationAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateGovernmentOrganisationAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateGovernmentOrganisationAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateGovernmentOrganisationAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(new Runnable() {
            //public void run() {
               // new CreateGovernmentOrganisationAdmin().setVisible(true);
            

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
