/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Admin;

import Business.Enterprise.Enterprise;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author ramvaghani
 */
public class ManageOrganizationWAJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageOrganizationWAJPanel
     */
    JPanel userProcessContainer;
    Enterprise enterprise;

    ManageOrganizationWAJPanel(JPanel userProcessContainer, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.enterprise=enterprise;
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        OrganizationJTable = new javax.swing.JTable();
        BackJBtn = new javax.swing.JButton();
        ViewOrganizationBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Manage Organization Work Area JPanel");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 11, -1, -1));

        OrganizationJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Organization Name", "Organization Type", "Address", "Contact No"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(OrganizationJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 67, 650, 170));

        BackJBtn.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        BackJBtn.setText("Back");
        BackJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackJBtnActionPerformed(evt);
            }
        });
        add(BackJBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, -1, -1));

        ViewOrganizationBtn.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        ViewOrganizationBtn.setText("View organization");
        ViewOrganizationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewOrganizationBtnActionPerformed(evt);
            }
        });
        add(ViewOrganizationBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 450, -1));
    }// </editor-fold>                        

    private void BackJBtnActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }                                        

    private void ViewOrganizationBtnActionPerformed(java.awt.event.ActionEvent evt) {                                                    
        // TODO add your handling code here:

        int SelectedRow = OrganizationJTable.getSelectedRow();
        if(SelectedRow<0){
            JOptionPane.showMessageDialog(null,"Please select a row from the table first","Warning", JOptionPane.WARNING_MESSAGE);
        }
        else{
            //Customer cr = (Customer)OrganizationJTable.getValueAt(SelectedRow,0);
            //ViewCustomer vpanel = new ViewCustomer(userProcessContainer,cr);
            //userProcessContainer.add("viewCustomer",vpanel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);

        }
    }                                                   


    // Variables declaration - do not modify                     
    private javax.swing.JButton BackJBtn;
    private javax.swing.JTable OrganizationJTable;
    private javax.swing.JButton ViewOrganizationBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration                   
}

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
