/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Security;

import Business.Ecosystem;
import Business.Enterprise.Enterprise;
import Business.Organisation.Organisation;
import Business.UserAccount.UserAccount;
import Interface.Garbage.CreateSocietyAdminWAJPanel;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author ankit
 */
public class SecurityEnterpriseWAJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SecurityEnterpriseWAJPanel
     */
    public SecurityEnterpriseWAJPanel() {
    }
    
    JPanel userProcessContainer;
    UserAccount account;
    Organisation organization;
    Enterprise enterprise;
    Ecosystem business;

    
    public SecurityEnterpriseWAJPanel(JPanel userProcessContainer, UserAccount account, Organisation organization, Enterprise enterprise, Ecosystem business) {
            initComponents();
            this.userProcessContainer=userProcessContainer;
            this.account=account;
            this.organization=organization;
            this.enterprise=enterprise;
            this.business=business;
            
            System.out.println("business in security="+business);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        manageorganisations = new javax.swing.JButton();
        ManageAdmins = new javax.swing.JButton();
        enterpriseReqJBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Manage Security Organisations");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 290, -1));

        manageorganisations.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        manageorganisations.setText("Manage Organisations");
        manageorganisations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageorganisationsActionPerformed(evt);
            }
        });
        add(manageorganisations, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 59, 290, -1));

        ManageAdmins.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        ManageAdmins.setText("Manage Admins of Organisations");
        ManageAdmins.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageAdminsActionPerformed(evt);
            }
        });
        add(ManageAdmins, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 290, -1));

        enterpriseReqJBtn.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        enterpriseReqJBtn.setText("Manage Work Request to Other Enterprise");
        enterpriseReqJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterpriseReqJBtnActionPerformed(evt);
            }
        });
        add(enterpriseReqJBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 290, -1));
    }// </editor-fold>                        

    private void manageorganisationsActionPerformed(java.awt.event.ActionEvent evt) {                                                    
        // TODO add your handling code here:
        CreateSecurityOrgJPanel igcsojp = new CreateSecurityOrgJPanel(userProcessContainer, account, organization, enterprise, business);
        userProcessContainer.add("CreateSecurityOrgJPanel", igcsojp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }                                                   

    private void ManageAdminsActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
//        CreateSecurityAdminJPanel igcsawjp = new CreateSecurityAdminJPanel(userProcessContainer, enterprise);
//        userProcessContainer.add("CreateSecurityAdminJPanel", igcsawjp);
//        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
//        layout.next(userProcessContainer);

        CreateSocietyAdminWAJPanel igcsawjp = new CreateSocietyAdminWAJPanel(userProcessContainer, account, organization, enterprise, business);
        userProcessContainer.add("CreateSocietyAdminWAJPanel", igcsawjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }                                            

    private void enterpriseReqJBtnActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        // TODO add your handling code here:
        SecurityEnterpriseWRJPanel igcsawjp = new SecurityEnterpriseWRJPanel(userProcessContainer, enterprise,account,business);
        userProcessContainer.add("SocietyEnterpriseWRJPanel", igcsawjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }                                                 


    // Variables declaration - do not modify                     
    private javax.swing.JButton ManageAdmins;
    private javax.swing.JButton enterpriseReqJBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton manageorganisations;
    // End of variables declaration                   
}

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
